{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: {{ .Values.nginx.serviceType }}
  selector:
    app: nginx
  ports:
  - port: {{ .Values.nginx.port }}
    targetPort: {{ .Values.nginx.port }}
    nodePort: {{ .Values.nginx.nodePort }}
{{- end }}
